dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
before_install:
  - sudo apt-get update -y
  - sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc
install:
  - ./configure
  - make
  - sudo make install
before_script:
  - sudo apt-get install cabal-install -y
  - cabal update
  - cabal install random
  - git clone https://github.com/jlab/gapc-test-suite.git
script:
  #- make test-unit  # works locally & in travis
  #- make test-paral  # works locally & in travis
  - make test-mod TRUTH_DIR=./gapc-test-suite/Truth TRUTH_SUFFIX=_ubuntu
  #- make test-regress
  #- make test-ambiguity
