dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
before_install:
  - sudo apt-get update -y
  - sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc
install:
  - ./configure
  - make
script:
  #- make test-unit
  - make test-paral
  #- make test-mod
  #- make test-regress
  #- make test-ambiguity
