dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
before_install:
  - sudo apt-get update -y
  - sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc
install:
  - ls -la /usr/
  - exit 1
  - ./configure
  - make
  - make install
before_script:
  - sudo apt-get install cabal-install -y
  - cabal update
  - cabal install random
  - cabal install hashtables
script:
  #- make test-unit
  - make test-paral
  #- make test-mod
  #- make test-regress
  #- make test-ambiguity
