name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc python3 python3-pip
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --prefix /gapc
    - name: make
      run: make -j 100
    - name: make install
      run: sudo make install
    - name: upload installation
      uses: actions/upload-artifact@v2
      with:
          name: prefix
          path: |
            /gapc

  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: download installation
      uses: actions/download-artifact@v2
      with:
          name: prefix
    - name: execute test
      run: make test-unit
     
    
