name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc python3 python3-pip
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --prefix $GITHUB_WORKSPACE
    - name: make
      run: make -j 100
    #- name: make install
    #  run: sudo make install
    - name: upload compile result
      uses: actions/upload-artifact@v2
      with:
          name: gapc
          path: |
            ./
            !.git/**
            !.github/**
            !debian/**
            !docker/**
            !documentation/**

  unit-tests:
    needs: compile
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: sudo apt-get install make libboost-all-dev libgsl-dev
    - name: download compile result
      uses: actions/download-artifact@v2
      with:
          name: gapc
    - name: execute test
      run: make test-unit
     
  paral-tests:
    needs: compile
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: sudo apt-get install make libboost-all-dev libgsl-dev ghc
    - name: Install ghc and cabal
      run: sudo apt-get install cabal-install
    - name: update cabal
      run: cabal update
    - name: add random Haskell lib
      run: cabal install random
    #- name: Checkout truth
    #  run: git clone https://github.com/jlab/gapc-test-suite.git $GITHUB_WORKSPACE
    - name: download compile result
      uses: actions/download-artifact@v2
      with:
          name: gapc
    - name: execute test
      run: make test-paral
     
    
