name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  compile_and_test:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies
      run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev ghc python3 python3-pip cabal-install
    - name: update cabal
      run: cabal update
    - name: add random Haskell lib
      run: cabal install --lib random
    - name: Checkout truth
      run: git clone https://github.com/jlab/gapc-test-suite.git $GITHUB_WORKSPACE
      
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --prefix $GITHUB_WORKSPACE
    - name: make
      run: make -j 100
    - name: make install
      run: sudo make install
      
    - name: test-unit
      run: make test-unit
    - name: test-paral
      run: make test-paral
    - name: test-mod
      run: make test-mod TRUTH_DIR=$GITHUB_WORKSPACE/gapc-test-suite/Truth TRUTH_SUFFIX=_ubuntu
    - name: test-regress
      run: make test-regress TRUTH_DIR=$GITHUB_WORKSPACE/gapc-test-suite/Truth
    - name: test-ambiguity
      run: make test-ambiguity TRUTH_DIR=$GITHUB_WORKSPACE/gapc-test-suite/Truth    
 
