name: test outside injection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, outside ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  gapc_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install flex bison make libboost-all-dev libgsl-dev python3 python3-pip

    - name: Checkout truth
      run: git clone --branch outside_v2 https://github.com/jlab/gapc-test-suite.git $GITHUB_WORKSPACE/../gapc-test-suite

    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --prefix $GITHUB_WORKSPACE

    - name: test-mod_outside
      run: make -j 2 test-mod_outside TRUTH_DIR=$GITHUB_WORKSPACE/../gapc-test-suite/Truth TRUTH_SUFFIX=_ubuntu

  gapc_osx:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies
      run: brew install bison@2.7 cmake boost gsl gnu-sed libomp gmp cabal-install
    - name: update cabal
      run: cabal update
    - name: add random Haskell lib
      run: cabal install --lib random
    - name: Checkout truth
      run: git clone --branch outside_v2 https://github.com/jlab/gapc-test-suite.git $GITHUB_WORKSPACE/../gapc-test-suite

    - uses: actions/checkout@v3
    - name: configure
      run: ./configure --prefix $GITHUB_WORKSPACE
    - name: patch configuration for OSX
      run: gsed -E "s|^YACC = .+$|YACC = /usr/local/opt/bison@2.7/bin/bison|" -i config.mf && gsed -E "s|^SED = .+$|SED = /usr/local/opt/gnu-sed/libexec/gnubin/sed|" -i config.mf && gsed -E "s/ -D_XOPEN_SOURCE=500 / /" -i config.mf && gsed -E "s/ -std=c\+\+17 / -std=c\+\+11 /" -i config.mf
    - name: make
      run: make -j 3
    - name: make install
      run: sudo make install

    - name: test-mod_outside
      run: make -j 2 test-mod_outside TRUTH_DIR=$GITHUB_WORKSPACE/../gapc-test-suite/Truth TRUTH_SUFFIX=_osx
